const corporativos = [
	// mock de lo que responde el back-end
	{
		id: 1,
		titulo: 'MINI EJECUTIVO',
		precio: 35.0,
		imagen:
			'https://firebasestorage.googleapis.com/v0/b/micanastaexpress-23ff9.appspot.com/o/corporativos%2FMINI%20EJECUTIVO%201.jpg?alt=media&token=8cb391a9-57f9-4b59-926c-64b199c3f801',
		descripcion: [
			'ELONGATED WOODEN BOX (OPTIONAL COMPANY LOGO)',
			'PERSONALIZED MESSAGE',
			'ORANGE JUICE',
			'STARBUCKS COFFEE',
			'GLASS WITH FRUITS',
			'HAM AND CHEESE SANDWICH LETTUCE, TOMATO AND HOUSE SAUCE',
			'OATMEAL COOKIES',
			'NECKER AND CUTLERY SET',
			'2 HELIUM BALLOONS (OPTIONAL)',
			'MINIMUM 5 UNITS FOR EACH ORDER.',
		],
		categoria: 'Corporativos',
	},
	{
		id: 2,
		titulo: 'MINI PINK BOX',
		precio: 55.0,
		imagen:
			'https://firebasestorage.googleapis.com/v0/b/micanastaexpress-23ff9.appspot.com/o/corporativos%2FMINI%20PINK%20BOX.jpg?alt=media&token=e4f1758a-0df9-45b0-adbf-380cb087d5b1',
		descripcion: [
			'BOX WITH ACETATE LID',
			'ORANGE JUICE',
			'3 MINI WAFFLES WITH STRAWBERRIES AND NUTELLA',
			'1 SERVING OF FRUIT',
			'2 BISCUITS AVAILABLE',
			'1 MINI FLORAL ARRANGEMENT',
			'1 NUTELLA',
			'DOES NOT INCLUDE BALLOON',
			'MINIMUM 3 UNITS PER ORDER',
		],
		categoria: 'Corporativos',
	},
	{
		id: 3,
		titulo: 'MINI BOX CAKE',
		precio: 55.0,
		imagen:
			'https://firebasestorage.googleapis.com/v0/b/micanastaexpress-23ff9.appspot.com/o/corporativos%2FMINI%20BOX%20CAKE.jpg?alt=media&token=aded764f-55cc-44d9-b811-53c03dee36ac',
		descripcion: [
			'CARTON BOX',
			'MINI CAKE',
			'YOGURT WITH CEREAL',
			'MINI FRUIT BOWL',
			'HAM CHEESE LETTUCE AND TOMATO SANDWICH',
			'BISCUITS',
			'CARD',
			'MINIMUM 3 UNITS PER ORDER',
		],
		categoria: 'Corporativos',
	},
	{
		id: 4,
		titulo: 'MINI BOX CHARCUTERIA',
		precio: 15.0,
		imagen:
			'https://firebasestorage.googleapis.com/v0/b/micanastaexpress-23ff9.appspot.com/o/corporativos%2FMINI%20BOX%20CHARCUTERIA.jpg?alt=media&token=889a44ee-389c-4d78-804c-b8dc8e475344',
		descripcion: [
			'SALAMI OR HAM',
			'STRAWBERRIES',
			'GRAPES',
			'KIWI',
			'CHEESE',
			'BISCUITS',
			'BOX WITH LID',
			'MINIMUM 15 UNITS PER ORDER.',
		],
		categoria: 'Corporativos',
	},
	{
		id: 5,
		titulo: 'LUXURY BRUNCH',
		precio: 65.0,
		imagen:
			'https://firebasestorage.googleapis.com/v0/b/micanastaexpress-23ff9.appspot.com/o/corporativos%2FLUXURY%20BRUNCH.jpg?alt=media&token=abe8570c-65de-4c94-9d60-92fe12921688',
		descripcion: [
			'WOODEN TRAY',
			'YOGURT WITH CEREAL',
			'MINI FRUIT BOWL',
			'HAM CHEESE LETTUCE AND TOMATO SANDWICH',
			'ORANGE JUICE',
			'STARBUCKS COFFEE',
			'BISCUITS',
			'CARD',
			'CHARCUTERIA TRAY',
			'MINIMUM 3 UNITS PER ORDER',
		],
		categoria: 'Corporativos',
	},
	{
		id: 6,
		titulo: 'MINI BRUNCH',
		precio: 29.99,
		imagen:
			'https://firebasestorage.googleapis.com/v0/b/micanastaexpress-23ff9.appspot.com/o/corporativos%2FMINI%20BRUNCH.jpg?alt=media&token=04be3c5a-bf1b-448c-83db-803ce450d592',
		descripcion: [
			'WOODEN BOX',
			'CHEESE PLATE (CHORCUTERIA)',
			'NUTS',
			'HATSU TEA OR ORANGE JUICE',
			'PERSONALIZED MESSAGE',
			'MINIMUM 5 UNITS PER ORDER.',
		],
		categoria: 'Corporativos',
	},
	{
		id: 7,
		titulo: 'REUNIÓN EXPRESS',
		precio: 130.0,
		imagen:
			'https://firebasestorage.googleapis.com/v0/b/micanastaexpress-23ff9.appspot.com/o/corporativos%2FREUNIÓN%20EXPRESS.jpg?alt=media&token=d60b6b5b-9d81-4a7d-91ed-7b75b4b0774e',
		descripcion: [
			'BREAKFAST FOR 5 PEOPLE',
			'5 HAM AND CHEESE CLUB SANDWICHES',
			'LETTUCE, TOMATO AND HOUSE SAUCE.',
			'5 ORANGE JUICES',
			'FRUIT BOWL FOR 5 PEOPLE',
			'BIG WAVE',
			'MINI CAKE',
			'5 PACKS OF OAT COOKIES',
			'MINI CHAMPAGNE OR WINE',
		],
		categoria: 'Corporativos',
	},
	{
		id: 8,
		titulo: 'CELEBRACIÓN EXPRESS',
		precio: 79.99,
		imagen:
			'https://firebasestorage.googleapis.com/v0/b/micanastaexpress-23ff9.appspot.com/o/corporativos%2FCELEBRACIÓN%20EXPRESS%201.jpg?alt=media&token=10febdee-268e-4243-987c-39aa8493122f',
		descripcion: [
			'WOODEN TRAY',
			'TABLECLOTH',
			'FERRERO ROCHER X3',
			'CLUB SANDWICH (CHEESE, HAM, LETTUCE, TOMATO AND HOUSE SAUCE)',
			'FRUIT CUP WITH YOGURT',
			'TEA OR ORANGE JUICE',
			'FLOWER BOUQUET',
			'OPTIONAL BUBBLE BALLOON',
			'PERSONALIZED MESSAGE',
		],
		categoria: 'Corporativos',
	},
];

export default corporativos;
